
name: CI/CD With Complex Tests

on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  name: Run Complex Tests
      runs-on: ubuntu-latest
      environment: 
        name: testing
        url: https://github.com
      steps:
        - uses: actions/checkout@v2
          with:
            ref: ${{ env.DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH }} # SHA that triggered your original job
        - name: Running Complex tests
          run: echo Test are running     