
name: CI/CD With Complex Tests

on:
  schedule:
    - cron:  '*/15 * * * *'    # At every 15th minute

jobs:
  name: Run Complex Tests
      runs-on: ubuntu-latest
      environment: 
        name: testing
        url: https://github.com
      steps:
        - uses: actions/checkout@v2
        - name: Running Complex tests
          run: echo Test are running     