
name: CI/CD With Complex Tests

on:
# Is this example the piepline runs  every 15th minute, but this value can be changed
  schedule:
    - cron:  '*/15 * * * *'    

jobs:
  name: Run Complex Tests
      runs-on: ubuntu-latest
      environment: 
        name: testing
        url: https://github.com
      steps:
        - uses: actions/checkout@v2
        - name: Running Complex tests
          run: echo Test are running     