
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    # Clone of the code
    - uses: actions/checkout@v1 
    - name: Linting
      run: echo Linting code.
    - name: Build 
      run: echo Building code
    - name: Unit Testing
      run: echo Run Unit testing
    - name: Run Code
      run: echo Coding is runnig
  deployment:
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: deploy
        # ...deployment-specific steps