
name: CI

on: [push]

jobs:
  development_evironment:
    name: Development
    runs-on: ubuntu-latest    
    steps:
    # Clone of the code
    - uses: actions/checkout@v1
      name: Clone code  
    - uses: cardinalby/export-env-action@v1
      name: Load Feature toogles
      with:
        envFile: './env/development/config.env'    
        expand: 'true'  
    - name: Linting
      run: echo Linting code.
    - uses: actions/setup-python@v2
      name : Build
    - name: Unit Testing
      run: echo Run Unit testing
    - uses: jannekem/run-python-script-action@v1
      name : Run Code
      with:
       script: |
          import os
          if os.environ.get('FEATURE1') == "True":
              print(os.environ.get('FEATURE1'))
          if os.environ.get('FEATURE2') == "True":
              print("Running FEATURE2")     
  deployment_integration:
    needs: development_evironment
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://github.com
    steps:
      - name: Deploy in Integration
        run: echo Coding is deployed
  integration_enviroment:
    needs: deployment_integration
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      name: Clone code 
    - uses: cardinalby/export-env-action@v1
      name: Load Feature toogles
      with:
        envFile: './env/integration/config.env'    
        expand: 'true'  
    - uses: jannekem/run-python-script-action@v1
      name : Run Code
      with:
       script: |
          import os
          if os.environ.get('FEATURE1') == "True":
              print(os.environ.get('FEATURE1'))
          if os.environ.get('FEATURE2') == "True":
              print("Running FEATURE2") 
    - name: Integration Testing
      run: echo Run Unit testing  
  deployment_testing:
    needs: integration_enviroment
    runs-on: ubuntu-latest
    environment: 
      name: integration
      url: https://github.com
    steps:
      - name: deploy
        run: echo Coding is deployed 
  testing_enviroment:
    needs: deployment_testing
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      name: Clone code 
    - uses: cardinalby/export-env-action@v1
      name: Load Feature toogles
      with:
        envFile: './env/testing/config.env'    
        expand: 'true'  
    - uses: jannekem/run-python-script-action@v1
      name : Run Code
      with:
       script: |
          import os
          if os.environ.get('FEATURE1') == "True":
              print(os.environ.get('FEATURE1'))
          if os.environ.get('FEATURE2') == "True":
              print("Running FEATURE2") 
    - name: Non-Functional Testing
      run: echo Run Non-Functinal Testing
    - name: Functional Testing
      run: echo Run Functinal Testing
  deployment_staging:
    needs: testing_enviroment
    runs-on: ubuntu-latest
    environment: 
      name: staging
      url: https://github.com
    steps:
      - name: deploy
        run: echo Coding is deployed   
  staging_enviroment:
    needs: deployment_staging
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
      name: Clone code 
    - uses: cardinalby/export-env-action@v1
      name: Load Feature toogles
      with:
        envFile: './env/staging/config.env'    
        expand: 'true'  
    - uses: jannekem/run-python-script-action@v1
      name : Run Code
      with:
       script: |
          import os
          if os.environ.get('FEATURE1') == "True":
              print(os.environ.get('FEATURE1'))
          if os.environ.get('FEATURE2') == "True":
              print("Running FEATURE2") 
    - name: Non-Functional Testing
      run: echo Run Non-Functinal Testing
    - name: Functional Testing
      run: echo Run Functinal Testing
  release:
      needs: staging_enviroment
      runs-on: ubuntu-latest
      environment: 
        name: Prodution 
        url: https://github.com
      steps:
        - name: deploy
          run: echo Coding is deployed
